#文件存储
#domain: http://101.201.125.13:80/awall
#domain: http://www.javae.cn:8088/awall
domain: http://localhost/awall
file:
#  uploadPath: /app/tem/
  uploadPath: E:/app/tem/
  staticAccessPath: /awall/upload/**
  accessPath: /upload/
server:
  port: 80
spring:
  datasource:
#    username: root
#    password: 123456
    username: awall
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql:///awall
    url: jdbc:mysql://81.70.207.162:3306/awall
mybatis:
  type-aliases-package: cn.awall.awalladmin.pojo
  mapper-locations: classpath*:cn/awall/awalladmin/dao/*.xml

#logging:
#  level:
#    com:
#      dandelion:
#        delivery:
#          admin:
#            mapper: debug
