#文件存储
domain: http://localhost:80
file:
  upload-path: E://app/
  staticAccessPath: /upload/**
  accessPath: /upload/
server:
  port: 80
spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///awall
mybatis:
  type-aliases-package: cn.awall.awalladmin.pojo
  mapper-locations: classpath*:cn/awall/awalladmin/dao/*.xml

logging:
  level:
    com:
      dandelion:
        delivery:
          admin:
            mapper: debug
